dependencies {
    api project(":support:support-domain")
    implementation project(":user:user-storage")
    // Spring Boot Starter WebFlux
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    // Spring Boot Starter WebSocket
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    // Reactor Core (리액티브 프로그래밍을 위한 필수 라이브러리)
    implementation 'io.projectreactor:reactor-core'
//    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb-reactive'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
