spring.application.name: chat-service
spring.profiles.active: local

spring:
  config:
    import:
      - monitoring.yml
      - logging.yml
      - chat-storage.yml
  web.resources.add-mappings: true

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  port: 19095

api:
  prefix: "/api/v1"

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live
