spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:19091  # Auth Service? ???? URI
          predicates:
            - Path=/api/v1/auth/**, /api/v1/health/**
        - id: user-service
          uri: http://localhost:19092
          predicates:
            - Path=/api/v1/users/**
        - id: lawyer-service
          uri: http://localhost:19093
          predicates:
            - Path=/api/v1/lawyers/**, /api/v1/reviews/**
        - id: contact-service
          uri: http://localhost:19094
          predicates:
            - Path=/api/v1/orders/**
server:
  port: 19090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
