server:
  port: 19090
spring:
  config:
    import:
      - redis.yml
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth:19091  # Auth Service? ???? URI
          predicates:
            - Path=/api/v1/auth/**, /api/v1/health/**
        - id: user-service
          uri: http://user:19092
          predicates:
            - Path=/api/v1/users/**, /feign/users/**
        - id: lawyer-service
          uri: http://lawyer:19093
          predicates:
            - Path=/api/v1/lawyers/**, /api/v1/reviews/**
        - id: contact-service
          uri: http://contact:19094
          predicates:
            - Path=/api/v1/contracts/**, /api/v1/posts/**
---
spring.config.activate.on-profile: local

spring:
  config:
    import:
      - redis.yml
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth:19091  # Auth Service? ???? URI
          predicates:
            - Path=/api/v1/auth/**, /api/v1/health/**
        - id: user-service
          uri: http://user:19092
          predicates:
            - Path=/api/v1/users/**, /feign/users/**
        - id: lawyer-service
          uri: http://lawyer:19093
          predicates:
            - Path=/api/v1/lawyers/**, /api/v1/reviews/**
        - id: contact-service
          uri: http://contact:19094
          predicates:
            - Path=/api/v1/contracts/**, /api/v1/posts/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

---
spring.config.activate.on-profile: dev

spring:
  application:
    name: gateway
  config:
    import:
      - redis.yml
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth:19091  # Auth Service? ???? URI
          predicates:
            - Path=/api/v1/auth/**, /api/v1/health/**
        - id: user-service
          uri: http://user:19092
          predicates:
            - Path=/api/v1/users/**, /feign/users/**
        - id: lawyer-service
          uri: http://lawyer:19093
          predicates:
            - Path=/api/v1/lawyers/**, /api/v1/reviews/**
        - id: contact-service
          uri: http://contact:19094
          predicates:
            - Path=/api/v1/contracts/**, /api/v1/posts/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/